AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"
